# Generated by Django 5.1.3 on 2024-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='product name')),
                ('description', models.TextField(verbose_name='product description')),
                ('price', models.IntegerField(verbose_name='product price')),
            ],
        ),
    ]
