# Generated by Django 5.1.3 on 2024-12-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product-images'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='reviewers name')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'bad'), (2, 'avg'), (3, 'good'), (4, 'very good'), (5, 'excellent')], default=3, verbose_name='product rating')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
