# Generated by Django 5.1.3 on 2024-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_description',
            field=models.TextField(default=''),
        ),
    ]
