# Generated by Django 5.1.3 on 2024-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_cart_product_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=30, verbose_name='category name')),
                ('description', models.TextField(default='blank')),
                ('photo', models.ImageField(default='default.jpg', upload_to='categoyr-images')),
            ],
        ),
    ]
