# Generated by Django 5.1.3 on 2024-12-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_cart_product_alter_cart_user_cartproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
