# Generated by Django 5.1.3 on 2024-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=15, verbose_name='username'),
        ),
    ]
