# Generated by Django 5.1.3 on 2024-12-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_orders_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
