# Generated by Django 5.1.3 on 2024-12-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_total',
            field=models.IntegerField(),
        ),
    ]
