# Generated by Django 5.1.3 on 2024-12-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_orders_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
