# Generated by Django 5.1.3 on 2024-12-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
