# Generated by Django 5.1.3 on 2024-12-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cart_cartproduct_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='net_amount',
            field=models.IntegerField(default=0),
        ),
    ]
