# Generated by Django 5.1.3 on 2024-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_cart_created_at_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='net_amount',
            field=models.IntegerField(default=0),
        ),
    ]
