# Generated by Django 5.1.3 on 2025-01-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='home/static/home/images/profile.jpg', upload_to='user-profile-pictures'),
        ),
    ]
