# Generated by Django 5.1.3 on 2025-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profile.jpg', upload_to='user-profile-pictures'),
        ),
    ]
