# Generated by Django 5.1.3 on 2025-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/profile.jpg', upload_to='user-profile-pictures'),
        ),
    ]
